<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Onestepcheckout
 * @version    1.3.11
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    var awOSCShipmentEnterpriseGiftWrap = new AWOnestepcheckoutShipmentEnterpriseGiftwrap({
        giftOptionsContainerSelector: "#aw-onestepcheckout-shipping-method-wrapper #allow-gift-options-container",
        saveGiftOptionsUrl: <?php echo Zend_Json::encode($this->getSaveGiftOptionsAjaxUrl());?>,
        addPrintedCardCheckboxSelector: "add-printed-card-<?php echo $this->getQuote()->getId(); ?>",
        giftWrapDesignSelectsSelector: "#allow-gift-options-for-order-container select[name*='giftwrapping'], #allow-gift-options-for-items-container select[name*='giftwrapping']",
        addGiftOptionsCheckboxesSelector: "#allow_gift_options, #allow_gift_options_for_order, #allow_gift_options_for_items",
        messageOptionsSelector: "#allow-gift-messages-for-order-container .input-box, #allow-gift-options-for-items-container .input-box",
        extraOptionsSelector: ".extra-options-container input"
    });
</script>